version: "3.9"

services:

  postgres_db_1:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wisercat_test_filters
    ports:
      - '5438:5432'
    volumes:
      - postgres_db_v1:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d

volumes:
  postgres_db_v1: